name: kheabia
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  rect_getter:
  simple_animations:
  page_transition:
  flutter_screenutil:
  shared_preferences:
  flutter_animated_dialog:
  progress_indicator_button:
  fluttertoast:
  permission_handler:
  cached_network_image:
  connectivity:
  animate_do:
  data_connection_checker:
  firebase_core: 
  firebase_auth: 
  provider:
  cloud_firestore:
  twitter_qr_scanner:
  animated_text_kit:
  intl:
  barcode_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
  
    - family: Changa
      fonts:
        - asset: assets/fonts/Changa-VariableFont_wght.ttf
  
